2020-07-10 08:24:04.506 [HikariPool-1 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=13h1m16s48ms398µs872ns).
2020-07-10 08:24:40.012 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:24:50.887 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:24:59.529 [HikariPool-1 housekeeper] WARN  com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=55s30ms263µs428ns).
2020-07-10 08:25:01.164 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:25:11.213 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:25:21.375 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:25:31.550 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:25:41.724 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:25:51.925 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:26:02.199 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:26:12.799 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:26:23.924 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:26:36.001 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:26:50.201 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:27:08.515 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:27:35.019 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:28:15.100 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:28:55.198 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:29:35.299 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:30:15.399 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:30:55.498 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 08:31:26.327 [SpringContextShutdownHook] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: java.util.concurrent.CancellationException
2020-07-10 08:32:57.991 [http-nio-8085-exec-1] WARN  com.zaxxer.hikari.util.DriverDataSource - Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
2020-07-10 13:11:24.290 [http-nio-8085-exec-1] WARN  com.zaxxer.hikari.util.DriverDataSource - Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
2020-07-10 16:16:41.295 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:16:51.587 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:17:01.753 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:17:11.852 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:17:21.947 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:17:32.047 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:17:42.234 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:17:52.452 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:18:02.746 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:18:13.347 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:18:24.447 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:18:36.550 [lettuce-nioEventLoop-6-1] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:18:50.746 [lettuce-nioEventLoop-6-2] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:19:08.950 [lettuce-nioEventLoop-6-3] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 16:19:35.350 [lettuce-nioEventLoop-6-4] WARN  io.lettuce.core.protocol.ConnectionWatchdog - Cannot reconnect to [192.168.30.10:6379]: connection timed out: /192.168.30.10:6379
2020-07-10 17:02:22.946 [http-nio-8085-exec-1] WARN  com.zaxxer.hikari.util.DriverDataSource - Registered driver with driverClassName=com.mysql.jdbc.Driver was not found, trying direct instantiation.
